name: Run name
run-name: Run by @{{ github.actor }}

on: push
jobs:
  print:
    name: sample job
    runs-on: ubuntu-latest
    steps:
      - name: sample step
        run: echo "hello world"
      - uses: actions/checkout@v4
